# GET persons
GET http://localhost:3001/api/persons

# GET db info
GET http://localhost:3001/info

# GET person (:id)
:id = 1
GET http://localhost:3001/api/persons/:id

# DELETE person (:id)
:id = 1
DELETE http://localhost:3001/api/persons/:id

# POST person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Desmond",
    "number": "001"
}
