# GET persons
GET http://localhost:3001/api/persons

# GET db info
GET http://localhost:3001/info

# GET person (:id)
:id = 61c997dac57bc1499fb27c30
GET http://localhost:3001/api/persons/:id

# DELETE person (:id)
:id = 61c997dac57bc1499fb27c30
DELETE http://localhost:3001/api/persons/:id

# POST person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Desmond",
    "number": "001"
}

# PUT person (:id)
:id = 61c99738c10080d54fef221f
PUT http://localhost:3001/api/persons/:id
Content-Type: application/json

{
    "name": "Desmond",
    "number": "002"
}
